---
- name: install apache server on centos 7
  hosts: web
  become: yes
  remote_user: semaphore
  become_method: sudo
  tasks: 
  - name: create dir
    file:
     dest: /home/semaphore/rajas
     state: present
     mode: 0644
