---
- name: install apache server on centos 7
  hosts: web
  become: yes
  remote_user: semaphore
  become_method: sudo
  tasks: 
  - name: httpd package install
    yum:
     name: httpd
     state: latest
